country = ['Bogota','Buenos Aires','Cape Town','Chiang Mai',
          'Hong Kong','Kuala Lumpur','Mexico City','New York City',
          'Phnom Penh','Rio de Janeiro','San Francisco','San Juan',
          'Sao Paulo','Siem Reap','Antwerp','Barcelona','Belgrade',
          'Cancun', 'Damascus', 'Dusseldorf',
          'Geneva', 'Ho Chi Minh City', 'Las Vegas', 'Luang Prabang',
          'Medellin', 'New Orleans', 'Niagara Falls', 'Panama City',
          'Santo Domingo','St Lucia', 'Turks and Caicos', 'Zagreb', 'Aarhus',
          'Beijing', 'Frankfurt', 'Lima','Managua', 'Milan', 'Nice', 'Paris',
          'Phuket', 'Puerto Vallarta', 'Santiago',
          'Sarajevo', 'Siem Reap', 'St Petersburg']
