cities = ['Aarhus', 'Amsterdam', 'Anguilla', 'Antwerp', 'Aruba',
        'Athens', 'Auckland', 'Bali', 'Bangalore', 'Bangkok',
        'Barcelona', 'Basel', 'Beijing', 'Beirut', 'Belgrade',
        'Bergen', 'Berlin', 'Bern', 'Bogota', 'Bordeaux',
        'Boston', 'Breckenridge', 'Brighton', 'Brisbane', 'Bruges',
        'Brussels', 'Bucharest', 'Budapest', 'Buenos Aires', 'Burgundy',
        'Cairo', 'Canberra', 'Cancun', 'Cannes', 'Cape Town',
        'Cardiff', 'Cartagena', 'Chengdu', 'Chiang Mai', 'Colombo',
        'Copenhagen', 'Cork', 'Cotswolds', 'Cyprus', 'Dakar',
        'Damascus', 'Denver', 'Doha', 'Dubai', 'Dublin',
        'Dubrovnik', 'Dusseldorf', 'Edinburgh', 'Fez', 'Florence',
        'Frankfurt', 'Galway', 'Geneva', 'Glasgow', 'Goa',
        'Gothenburg', 'Graz', 'Hamburg', 'Hanoi', 'Helsinki',
        'Ho Chi Minh City', 'Hong Kong', 'Honolulu', 'Ibiza', 'Innsbruck',
        'Istanbul', 'Izmir', 'Jaipur', 'Jamaica', 'Johannesburg',
        'Kauai', 'Kiev', 'Kolkata', 'Krakow', 'Kuala Lumpur',
        'Kyoto', 'Las Vegas', 'Lima', 'Lisbon', 'Liverpool',
        'Ljubljana', 'London', 'Luang Prabang', 'Macau', 'Madrid',
        'Malta', 'Managua', 'Marrakesh', 'Maui', 'Medellin',
        'Melbourne', 'Memphis', 'Mendoza', 'Mexico City', 'Milan',
        'Milwaukee', 'Monaco', 'Montevideo', 'Montreal', 'Moscow',
        'Mumbai', 'Munich', 'Nairobi', 'Nassau', 'New Orleans',
        'New York City', 'Niagara Falls', 'Nice', 'Oaxaca', 'Orlando',
        'Osaka', 'Oslo', 'Ottawa', 'Oxford', 'Palermo',
        'Panama City', 'Paris', 'Penang', 'Perugia', 'Philadelphia',
        'Phnom Penh', 'Phoenix', 'Phuket', 'Porto', 'Prague',
        'Puebla', 'Puerto Vallarta', 'Quito', 'Reykjavik', 'Richmond',
        'Riga', 'Rio de Janeiro', 'Rome', 'Salta', 'Salvador',
        'Salzburg', 'San Francisco', 'San Juan', 'Santiago', 'Santo Domingo',
        'Sao Paulo', 'Sarajevo', 'Seattle', 'Seoul', 'Seville',
        'Shanghai', 'Siem Reap', 'Singapore', 'Sofia', 'Split',
        'St Lucia', 'St Petersburg', 'Stockholm', 'Sydney', 'Taipei',
        'Tallinn', 'Tbilisi', 'Thessaloniki', 'Tokyo', 'Toronto',
        'Trinidad', 'Turin', 'Turks and Caicos', 'Valencia', 'Vancouver',
        'Venice', 'Verona', 'Vienna', 'Vientiane', 'Vieques',
        'Vilnius', 'Warsaw', 'Yangon', 'Zagreb', 'Zanzibar', 'Zurich']

countries = ['Denmark','The Netherlands', 'United Kingdom','Belgium', 'The Netherlands',
            'Greece', 'New Zealand', 'Indonesia', 'India','Thailand',
            'Spain', 'Switzerland', 'China', 'Lebanon', 'Serbia',
            'Norway', 'Germany', 'Switzerland','Colombia','France',
            'USA', 'USA', 'England','Australia', 'Belgium',
            'Belgium','Romania', 'Hungary', 'Argentina', 'France',
            'Egypt', 'Australia','Mexico', 'France','South Africa',
            'Wales', 'Colombia', 'China', 'Thailand', 'Sri Lanka',
            'Denmark', 'Ireland','England', 'Cyprus','Senegal',
            'Syria', 'USA','Qatar','United Arab Emirates','Ireland',
            'Croatia','Germany','Scotland','Morocco', 'Italy',
            'Germany', 'Ireland', 'Switzerland','Scotland','India',
            'Sweden','Austria','Germany','Vietnam','Finland',
            'Vietnam','Hong Kong','USA','Spain','Austria',
            'Turkey','Turkey','India','Jamaica','South Africa',
            'USA','Ukraine', 'India', 'Poland','Malaysia',
            'Japan', 'USA','Peru', 'Portugal','England',
            'Slovenia', 'England','Laos', 'China','Spain',
            'Malta', 'Nicaragua', 'Morocco', 'USA', 'Colombia',
            'Australia','USA','Argentina', 'Mexico','Italy',
            'USA', 'Monaco','Uruguay', 'Canada', 'Russia',
            'India', 'Germany', 'Kenya', 'The Bahamas','USA',
            'USA', 'Canada', 'France','Mexico','USA',
            'Japan', 'Norway', 'Canada', 'England','Italy',
            'Panama','France','Malaysia', 'Italy', 'USA',
            'Cambodia','USA','Thailand', 'Portugal', 'Czech Republic',
            'Mexico', 'Mexico', 'Ecuador', 'Iceland','USA',
            'Latvia','Brazil', 'Italy','Argentina','Brazil',
            'Austria','USA','Puerto Rico', 'Chile','Dominican Republic',
            'Brazil','Bosnia and Herzegovina','USA', 'South Korea', 'Spain',
            'China','Cambodia', 'Singapore','Bulgaria', 'Croatia',
            'St Lucia', 'Russia', 'Sweden', 'Australia', 'Taiwan',
            'Estonia', 'Georgia','Greece','Japan', 'Canada',
            'Trinidad and Tobago','Italy', 'Turks and Caicos','Spain', 'Canada',
            'Italy', 'Italy','Austria','Laos', 'Puerto Rico',
            'Lithuania', 'Poland', 'Myanmar', 'Croatia', 'Tanzania', 'Switzerland']
